name = "resell-platform"
compatibility_date = "2026-05-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "resell-platform-db"
database_id = "c98b0503-52e1-4cac-ba21-fede0bb57d78"
migrations_dir = "migrations"
